name = "ai_project_ui"
type = "javascript"

account_id = "your-cloudflare-account-id"
workers_dev = true
compatibility_date = "2023-10-01"

[site]
bucket = "./public"
entry-point = "workers-site"

[env.production]
route = "your-domain.com/*"
zone_id = "your-zone-id"
